[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4.9.0"
serde = "1.0.210"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-async-std"] }
